- hosts: task-tracker-server
  become: yes

  tasks:

    - name: update apt
      apt:
        update_cache: yes

    - name: install docker and docker compose
      apt:
        name:
          - docker.io
          - docker-compose-plugin
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes