name: build-and-deploy

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_number }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/task_tracker:${IMAGE_TAG} \
          -f docker/Dockerfile .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/task_tracker:${IMAGE_TAG}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy docker-compose to server
        run: |
          scp -o StrictHostKeyChecking=no docker/docker-compose.yml \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/docker-compose.yml

      - name: Deploy container
        run: |

          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd /home/ubuntu

          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

          sed -i "s|IMAGE_TAG|${IMAGE_TAG}|g" docker-compose.yml

          docker compose pull
          docker compose up -d

          EOF