name: rollback

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to rollback"
        required: true

jobs:

  rollback:

    runs-on: ubuntu-latest

    steps:

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Rollback deployment
        run: |

          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd /home/ubuntu

          sed -i "s|task_tracker:.*|task_tracker:${{ github.event.inputs.tag }}|g" docker-compose.yml

          docker compose pull
          docker compose up -d

          EOF